INSERT INTO Usuario (NickName, Password) VALUES ('fer32', '345677');
INSERT INTO Usuario (NickName, Password) VALUES ('ali89', 'h678eb');
INSERT INTO Usuario (NickName, Password) VALUES ('inci', 'ab7nos');
INSERT INTO Usuario (NickName, Password) VALUES ('alu78', 'enmi09');
INSERT INTO Usuario (NickName, Password) VALUES ('mary', 'nimo09');
INSERT INTO Usuario (NickName, Password) VALUES ('lupita', 'llegu25');
INSERT INTO Usuario (NickName, Password) VALUES ('mitz', 'miry90');
INSERT INTO Usuario (NickName, Password) VALUES ('brenda', 'boom78');
INSERT INTO Usuario (NickName, Password) VALUES ('alo56', 'tyni79');
INSERT INTO Usuario (NickName, Password) VALUES ('chuy56', 'pollo67');

INSERT INTO Marca (NombreMarca) VALUES ('nes1');
INSERT INTO Marca (NombreMarca) VALUES ('kello2');
INSERT INTO Marca (NombreMarca) VALUES ('pep3');
INSERT INTO Marca (NombreMarca) VALUES ('dano4');
INSERT INTO Marca (NombreMarca) VALUES ('colg5');
INSERT INTO Marca (NombreMarca) VALUES ('Mar6');
INSERT INTO Marca (NombreMarca) VALUES ('hein7');
INSERT INTO Marca (NombreMarca) VALUES ('ferre8');
INSERT INTO Marca (NombreMarca) VALUES ('skip9');
INSERT INTO Marca (NombreMarca) VALUES ('rena10');

INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('pieza', 'obrto individual');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('unidad', 'cantidad especifica');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('caja', 'empaque con varias unidades');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('docena', '12 unidades');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('centena', '100 unidades');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('paquete', 'grupo de articulos');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('centimetro', 'unidad de longitud pequena');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('cuartillo', 'unidad de volumen equivalente a un cuarto de galon');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('pliego', 'unidad usada para el papel o el carton');
INSERT INTO Unidad (NombreUnidad, Descripcion) VALUES ('pie', 'unidad de longitud');

INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Distribuidora XYZ', 'Proveedor21', 'Direccion21', '3334567890');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Suministros ABC', 'Proveedor22', 'Direccion22', '3334567891');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Importaciones Global', 'Proveedor23', 'Direccion23', '1234432892');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Electro Hogar', 'Proveedor24', 'Direccion24', '1235557893');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Muebles y Mas', 'Proveedor25', 'Direccion25', '1222567894');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Textiles del Norte', 'Proveedor26', 'Direccion26', '1234560005');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Super Alimentos', 'Proveedor27', 'Direccion27', '1234333896');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Tecnologia Expres', 'Proveedor28', 'Direccion28', '1234555897');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Geniuss', 'Proveedor29', 'Direccion29', '1234447898');
INSERT INTO Proveedor (Compania, NombreProveedor, Direccion, Celular) VALUES ('Tecno Plus', 'Proveedor30', 'Direccion30', '1234567449');

INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-03-01', 21);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-02',22);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-03', 23);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-04',24);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-05', 25);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-06', 26);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-07', 27);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-08', 28);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-02-09', 29);
INSERT INTO FacturaCompra (FechaCompra, ProveedorId) VALUES ('2025-03-10', 30);

INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (21, 21);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (22, 22);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (23, 23);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (24, 24);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (25, 25);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (26, 26);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (27, 27);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (28, 28);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (29, 29);
INSERT INTO MarcaProveedor (MarcaId, ProveedorId) VALUES (30, 30);

INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Jorge', 'Martinez', 'Direccion21', '1234564490');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Miguel', 'Martinez', 'Direccion22', '1233567891');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Maria', 'Medina', 'Direccion23','3214567892');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Carlos', 'Bautimez', 'Direccion24', '1234007893');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Hannia', 'Gonzalez', 'Direccion25', '1211567894');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Merari', 'Pastelin', 'Direccion26', '1236667895');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Karen', 'Garcia', 'Direccion27', '1235567896');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Pedro', 'Ramirez', 'Direccion28', '1222567897');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Ana', 'Calleja', 'Direccion29', '1234512898');
INSERT INTO Cliente (Nombre, Apellido, Direccion, Celular) VALUES ('Aniel', 'Hernandez', 'Direccion30', '1324567899');

INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-01', 21);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-02', 22);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-03', 23);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-04', 24);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-05', 25);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-06', 26);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-07', 27);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-08', 28);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-09', 29);
INSERT INTO FacturaVenta (FechaVenta, ClienteId) VALUES ('2025-02-10', 30);

INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img31.jpg', 'Imagen31');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img32.jpg', 'Imagen32');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img33.jpg', 'Imagen33');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img34.jpg', 'Imagen34');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img35.jpg', 'Imagen35');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img36.jpg', 'Imagen36');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img37.jpg', 'Imagen37');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img38.jpg', 'Imagen38');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img39.jpg', 'Imagen39');
INSERT INTO Imagen (Ruta, Nombre) VALUES ('/images/img40.jpg', 'Imagen40');

INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (101.0, 151.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (202.0, 252.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (303.0, 353.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (404.0, 445.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (505.0, 556.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (606.0, 656.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (707.0, 757.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (808.0, 858.0, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (909.0, 95.90, TRUE);
INSERT INTO Precio (PrecioCompra, PrecioVenta, Active) VALUES (110.0, 115.0, TRUE);
 
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (11, 11, 11, 11, 11, 'Router');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (12, 12, 12, 12, 12, 'Switch');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (13, 13, 13, 13, 13, 'Gabinete');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (14, 14, 14, 14, 14, 'Targeta de memoria');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (15, 15, 15, 15, 15, 'Altavoces');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (16, 16, 16, 16, 16, 'Targeta de sonido');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (17, 17, 17, 17, 17, 'Targeta de red');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (18, 18, 18, 18, 18, 'Sistema de enfriamento liquido');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (19, 19, 19, 19, 19, 'Adaptador wifi');
INSERT INTO Producto (MarcaId, PrecioId, UnidadId, ImagenId, ProveedorId, Descripcion) VALUES (20, 20, 20, 20, 20, 'Bateria para laptop');
 
INSERT INTO ProductoFactura (ProductoId) VALUES (26);
INSERT INTO ProductoFactura (ProductoId) VALUES (27);
INSERT INTO ProductoFactura (ProductoId) VALUES (28);
INSERT INTO ProductoFactura (ProductoId) VALUES (29);
INSERT INTO ProductoFactura (ProductoId) VALUES (30);
INSERT INTO ProductoFactura (ProductoId) VALUES (31);
INSERT INTO ProductoFactura (ProductoId) VALUES (32);
INSERT INTO ProductoFactura (ProductoId) VALUES (33);
INSERT INTO ProductoFactura (ProductoId) VALUES (34);
INSERT INTO ProductoFactura (ProductoId) VALUES (35);

INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (31, 31);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (32, 32);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (33, 33);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (34, 34);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (35, 35);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (36, 36);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (37, 37);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (38, 38);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (39, 39);
INSERT INTO ProductoProveedor (ProductoId, ProveedorId) VALUES (40, 40);

INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (31, 31);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (32, 32);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (33, 33);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (34, 34);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (35, 35);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (36, 36);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (37, 73);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (38, 38);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (39, 39);
INSERT INTO ProductoImagen (ProductoId, ImagenId) VALUES (40, 40);
